services:
  linuxqq:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/sion10032/kasmweb/qq:latest
    container_name: linuxqq
    ports:
      - "6901:6901"
    environment:
      # KasmVNC web 登录密码
      - VNC_PW=password
      # 桌面分辨率
      - VNC_RESOLUTION=1280x720
    volumes:
      - ./data:/home/kasm-user
    # Electron/QQ 需要较大共享内存
    shm_size: '2gb'
    restart: unless-stopped
